spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 34064351736-j1htmlohgrv2r7gdghdee3cahj1msaar.apps.googleusercontent.com
            client-secret: Kz0oZgjG-w4buCmNSQcziylY
            scope: 
            - profile
            - email